const categories = [
  "Housing",
  "Utilities",
  "Groceries",
  "Dining",
  "Transportation",
  "Healthcare",
  "Entertainment",
  "Shopping",
  "Debt",
  "Education",
  "Travel",
  "Insurance",
  "Childcare",
  "Savings",
  "Investments",
  "Gifts",
  "Donations",
  "Pets",
  "Salary",
  "Business Income",
  "Rental Income",
  "Government Benefits",
  "Freelancing",
  "Pension",
  "Grants",
];
export default categories;
